
-- Generated by ORDS REST Data Services 21.4.0.r3481956
-- Schema: personalproject  Date: Thu Sep 14 01:34:52 2023 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'personalproject',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'personalproject',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'uat.personalproject.com',
      p_base_path      => '/api/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'uat.personalproject.com',
      p_pattern        => 'pdf/{APPID}',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'uat.personalproject.com',
      p_pattern        => 'pdf/{APPID}',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
  v_length    NUMBER;
  v_file_name VARCHAR2(200) := ''termsandconditions'';
  v_pdf_file  BLOB;
  v_mime      VARCHAR2(48) := ''application/pdf'';
BEGIN
  --
  v_file_name := ''termsandconditions'' || ''.pdf'';
  BEGIN
    SELECT  DTAC_TAC, dbms_lob.getlength(DTAC_TAC)
    INTO    v_pdf_file, v_length       
    FROM    personalproject_10_DOXTAC
    WHERE   row_key = :APPID;
   -- WHERE   row_key = ''888'';
    htp.init;
    OWA_UTIL.MIME_HEADER(v_mime, FALSE);
    htp.p(''Content-Disposition: inline; filename="'' || v_file_name || ''"'');
    owa_util.http_header_close;
    wpg_docload.download_file(v_pdf_file);
    apex_application.g_unrecoverable_error:= true;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      v_pdf_file  := EMPTY_BLOB();
      v_length    := dbms_lob.getlength(v_pdf_file);
      v_file_name := ''file_not_found.pdf'';
    WHEN OTHERS THEN
      v_pdf_file  := EMPTY_BLOB();
      v_length    := dbms_lob.getlength(v_pdf_file);
      v_file_name := ''file_not_found.pdf'';
  END;    
  --

  --
end;');

    
        
COMMIT;

END;